name = "hestia-site"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[[d1_databases]]
binding = "DB"
database_name = "hestia-site-db"
database_id = "2921747a-bd8e-4325-8445-9e34fa95afe6"
